---

- hosts: ios
  tasks:
     - name: Update Routes
       cisco.ios.ios_static_routes:
         config:
           - address_families:
             - afi: ipv4
               routes:
                 - dest: "{{ IPCIDR }}"
                   next_hops:
                     - forward_router_address: "{{ NEXTHOP }}"
                       name: inserted_via_IAS
                       distance_metric: 110
                       tag: 40
         state: merged  
     - name: Gather facts of static routes
       cisco.ios.ios_static_routes:
         config:
         state: gathered
     - name: Print all available facts
       ansible.builtin.debug:
         var: ansible_network_resources
