---

- hosts: ios
  vars:
    update: "Nothing For Today"
  tasks:
     - name: Gather IOS Facts
       cisco.ios.ios_facts:
         gather_subset: all
         gather_network_resources: all
     - name: Update banner
       cisco.ios.ios_banner:
         banner: login
         text: |
            NFD Banner Update
            Update Details - {{ update }}
            Banner Last Upated - {{ now(utc=true,fmt='%Y-%m-%d %H:%M:%S') }}
            Host -  {{ansible_net_hostname}}
     - name: Print Stuff
       debug:
          msg: "{{ ansible_facts }}"
