---

- hosts: ios
  tasks:
     - name: Update Routes
       cisco.ios.ios_static_routes:
         config:
           - address_families:
             - afi: ipv4
               routes:
                 - dest: "{{ IPCIDR }}"
                   next_hops:
                     - forward_router_address: "{{ NEXTHOP }}"
                       name: inserted_via_IAS
                       distance_metric: 110
                       tag: 40
         state: merged  
     - name: Gather facts of static routes
       cisco.ios.ios_static_routes:
         config:
         state: gathered
     - name: Gather IOS Facts
       cisco.ios.ios_facts:
         gather_subset: all
         gather_network_resources: all
     - name: Print Stuff
       debug:
          msg: "{{ ansible_facts.network_resources }}"
